spring:
  application:
    name: clinica-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/clinica_db
    username: postgres
    password: clinica

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /api/*
  swagger-ui:
    use-root-path: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080