spring:
  application:
    name: clinica-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/clinica_db
    username: postgres
    password: clinica

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true


spring-doc:
  paths-to-match:
    - /api/**/v1/** # Seus endpoints versionados (como medicos/v1)
    - /api/* # Inclui /api/home, /api/login, /api/login-error, /api etc.
  swagger-ui:
    use-root-path: true

server:
  port: 8080